### PR TITLE
Fix issue 665

### LINKED ISSUE #665: cell formula refering to DefinedName is not calculated correctly
**Description**

Here's a unit test to show the issue:

```golang
func TestCalcCellValueWithDefinedName(t *testing.T) {
	cellData := [][]interface{}{
		{1, 4, nil, "Month", "Team", "Sales"},
	}
	prepareData := func() *File {
		f := NewFile()
		for r, row := range cellData {
			for c, value := range row {
				cell, _ := CoordinatesToCellName(c+1, r+1)
				assert.NoError(t, f.SetCellValue("Sheet1", cell, value))
			}
		}
		assert.NoError(t, f.SetDefinedName(&DefinedName{Name: "ref_to_sheet1_a1", RefersTo: "Sheet1!A1", Scope: "Workbook"}))
		return f
	}
	f := prepareData()
	assert.NoError(t, f.SetCellFormula("Sheet1", "C1", "=ref_to_sheet1_a1"))
	_, err := f.CalcCellValue("Sheet1", "C1")
	assert.NoError(t, err)
}
```

**Describe the results you received:**

```text
=== RUN   TestCalcCellValueWithDefinedName

    TestCalcCellValueWithDefinedName: calc_test.go:817: 
        	Error Trace:	calc_test.go:817
        	Error:      	Received unexpected error:
        	            	#NAME?
        	Test:       	TestCalcCellValueWithDefinedName
--- FAIL: TestCalcCellValueWithDefinedName (0.00s)
FAIL
```

**Describe the results you expected:**

Successful unit test

**Output of `go version`:**

```text
go version go1.14.4 windows/amd64
```

**Excelize version or commit ID:**

```text
Excelize 2.2.0 or commit ID 0aa15106947965bdae9daae7571a4a3f569bf32d
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

Windows 10

### PR DESCRIPTION
**Pull request by jaby**
# PR Details

## Description

Here is a possible fix for issue   #665

Side note: 

Another (better?) way to fix this would be to introduce  a new `func (f *File) GetDefinedName() map[string]DefinedName` (or replace `func (f *File) GetDefinedName() []DefinedName` to return a map ?) This to avoid having to loop through the DefinedNames array...

## Motivation and Context

To fix #665

## How Has This Been Tested

See unit test in issue 665

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: calc.go [hunk 1]
```diff
@@ -458,6 +458,12 @@ func isOperatorPrefixToken(token efp.Token) bool {
 func (f *File) parseToken(sheet string, token efp.Token, opdStack, optStack *Stack) error {
 	// parse reference: must reference at here
 	if token.TSubType == efp.TokenSubTypeRange {
+		for _, definedName := range f.GetDefinedName() {
+			if definedName.Name == token.TValue {
+				token.TValue = definedName.RefersTo
```
Comment (xuri) [inline calc.go:463]: The scope of defined name should be checked here.

Comment (jaby) [reply calc.go:463]: It's no entirely clear to me which checks you would like to have?

The only thing I can think of is this:
I made a small xlsx file with 2 DefinedNames with the same name, one with Sheet scope the other with workbook scope. In this case Excel seems to calculate the value using the sheet scope, so presumably this should be the rule.  I have pushed the pull request accordingly. (Note: there was an additional change in sheet.go line 1424 needed, otherwise the workbook scope was lost)

Or do you have other/additional checks in mind?

**Comment by xuri** [comment]
LGTM, @jaby thanks very much for your contribution.
